const seedData2 = [
{Author: null, Quote: "Nobody is impressed with how good your excuses are."},
{Author: null, Quote: "Excuses are another way of saying, “I have no power or control over my life.”"},
{Author: null, Quote: "Laziness is evil."},
{Author: null, Quote: "To live a creative life, we must lose our fear of being wrong."},
{Author: null, Quote: "You can’t make excuses and money. Which is it going to be?"},
{Author: null, Quote: "You can have results or you can have your excuses. You cannot have both."},
{Author: "Brene Brown", Quote: "If you own this story you get to write the ending."},
{Author: null, Quote: "Procrastination is the grave in which opportunity is buried."},
{Author: "Buddha", Quote: "The trouble is, you think you have time."},
{Author: "Luis Galarza", Quote: "Success is what comes after your stop making excuses."},
{Author: "Alexander Pope", Quote: "An excuse is worse and more terrible than a lie; for an excuse is a lie guarded."},
{Author: null, Quote: "When you’re good at making excuses, it’s hard to excel at anything else. -John L. Mason"},
{Author: "Stephen Richards", Quote: "Making excuses is one of a host of self-defeating behaviors and mental patterns that can block your success."},
{Author: "Steven Grayhm", Quote: "Excuses are the tools with which persons with no purpose in view build for themselves great monuments of nothing."},
{Author: null, Quote: "When I lost all of my excuses I found my results."},
{Author: null, Quote: "Are your excuses more important than your dreams?"},
{Author: "Robin Sharma", Quote: "Your excuses are just the lies your fears have sold you."},
{Author: null, Quote: "If you want to reach your goals you must shrink the size of your but."},
{Author: null, Quote: "Nobody cares about your excuses. Nobody pities you for procrastinating. Nobody will cuddle you because you feel like being lazy. It’s your life. Change it."},
{Author: null, Quote: "No more excuses, no more wasting of precious time, for now is a good a time as any, to begin doing what matters most."},
{Author: null, Quote: "There are only two options: Make progress or make excuses."},
{Author: null, Quote: "Nobody is impressed with how good your excuses are."},
{Author: null, Quote: "One day your life will flash before your eyes. Make sure it’s worth watching."},
{Author: null, Quote: "The only person who is truly holding you back is you. No more excuses. It’s time to change. Time to live life at a new level rise higher."},
{Author: null, Quote: "The only thing standing between you and your goal is the bullshit story you keep telling yourself."},
{Author: "C.C. Chapman", Quote: "An excuse is nothing more than a self-imposed roadblock."},
{Author: "PowerPlug!", Quote: "Maturity comes when you stop making excuses and start making changes."},
{Author: "Kenneth Blanchard", Quote: "There’s a difference between interest and commitment. When you’re interested in doing something, you do it only when it’s convenient. When you’re committed to something, you accept no excuses; only results."},
{Author: null, Quote: "If you want it, you’ll find a way. If you don’t, you’ll find an excuse."},
{Author: null, Quote: "Replace excuses with effort replace laziness with determination and everything else will fall into place."},
{Author: null, Quote: "Many things aren’t equal but everyone gets the same 24 hours a day, 7 days a week. We make time for what we truly want."},
{Author: null, Quote: "Excuses will always be there for you, opportunity won’t."},
{Author: null, Quote: "The ones who find happiness are the ones who don’t make excuses. If it’s broken, they fix it… if it’s wrong, they make it right."},
{Author: "Henry Ford", Quote: "You can’t build a reputation on what you’re going to do."},
{Author: null, Quote: "Nobody is too busy, it’s just a matter of priorities."},
{Author: null, Quote: "Don’t make excuses for why you can’t get it done. Focus on all the reasons why you must make it happen."},
{Author: "Dr Steve Maraboli", Quote: "No more excuses or procrastination! Stop allowing your days to be stolen by busy nothingness."},
{Author: "Dani Johnson", Quote: "Excuses are well planned lies!"},
{Author: null, Quote: "Excuses. They are for people who don’t want it bad enough."},
{Author: null, Quote: "Excuses are for the weak. Responsibility is for the strong."},
{Author: "Unknown", Quote: "Excuses are the nails used to build the house of failure."},
{Author: null, Quote: "Excuses are lies we tell ourselves so that it doesn’t have to be our fault."},
{Author: null, Quote: "Excuses are for people who don’t want it bad enough."},
{Author: "George Washington Carver", Quote: "Ninety-nine percent of the failures come from people who have the habit of making excuses."},
{Author: null, Quote: "Instead of feeding myself excuses why I can’t, I give myself reasons why I can."},
{Author: null, Quote: "I don’t have time is the grown-up version of the dog ate my homework."},
{Author: null, Quote: "Sorry, I can’t today. My sister’s friend’s mother’s grandpa’s brother’s grandson’s uncle’s fish died, and yes it was tragic."},
{Author: null, Quote: "Never make excuses. Always wake up with a smile knowing that today you are going to have fun accomplishing what others are too afraid to do."},
{Author: null, Quote: "Nobody cares about your excuses. Nobody pities you for procrastinating. Nobody is going to cuddle you because you are lazy. It’s your ass. You move it."},
{Author: null, Quote: "If it is important to you, you will find a way. If not, you’ll find an excuse."},
{Author: "Ben Franklin", Quote: "He that is good at making excuses is seldom good for anything else."},
{Author: null, Quote: "The first step of change is to become aware of your own bullshit."},
{Author: "#bossbabeTM", Quote: "If you are confused about why you aren’t where you want to be, you need to write down a list of your excuses and realize everything on that list is why."},
{Author: null, Quote: "A day has enough hours. You just have too many excuses."},
{Author: null, Quote: "Stop saying I can’t. You can. You just choose not to."},
{Author: null, Quote: "Take responsibility and initiative for yourself. Stop blaming your circumstances on what you are able to change."},
{Author: null, Quote: "The only person who is truly holding you back is you. No more excuses, it’s time to change. It’s time to live life at a new level."},
{Author: null, Quote: "While you are still waiting to find an easy way (or the perfect time) someone else is already getting results because they decided making progress is more important than making excuses."},
{Author: null, Quote: "Be stronger than your excuses."},
{Author: null, Quote: "Be willing to walk alone. Many who started with you won’t finish with you."},
{Author: null, Quote: "Never allow waiting to become a habit. Live your dreams and take risks. Life is happening now."},
{Author: "Chi Chi Rodriguez", Quote: "Don’t look for excuses to lose. Look for excuses to win."},
{Author: "Mason Cooley", Quote: "Excuses change nothing, but make everyone feel better."},
{Author: null, Quote: "Someone once told me not to bite off more than I can chew. I said I’d rather choke on greatness than nibble on mediocrity."},
{Author: null, Quote: "It doesn’t matter whether you are pursuing success in business, sports, the arts, or life in general: The bridge between wishing and accomplishing is discipline. — Harvey Mackay"},
{Author: null, Quote: "Nothing in the world is more common than unsuccessful people with talent."},
{Author: "Agatha Christie", Quote: "To rush into explanations (excuses) is always a sign of weakness."},
{Author: "Lorii Myers", Quote: "Once your excuses are gone, you will simply have to settle for being awesome!"},
{Author: "John Wooden", Quote: "Never make excuses. Your friends don’t need them and your foes won’t believe them."},
{Author: null, Quote: "You will get what you want, when you stop making excuses on why you don’t have it."},
{Author: null, Quote: "Rule your mind or it will rule you. — Horace"},
{Author: "American Proverb", Quote: "Excuses are merely nails used to build a house of failure."},
{Author: "Sophocles", Quote: "It is a painful thing to look at your own trouble and know that you yourself and no one else has made it."},
{Author: "Mark Twain", Quote: "There are thousands of excuses for every failure, but never a good reason."},
{Author: null, Quote: "Bad things are always going to happen in life. People will hurt you. But you can’t use that as an excuse to fail or to hurt someone back. You’ll only hurt yourself."},
{Author: "Natalie Goldberg", Quote: "This is your life. You are responsible for it. You will not live forever. Don’t wait."},
{Author: null, Quote: "When there is a hill to climb, don’t think that waiting will make it smaller."},
{Author: "Doug Hall", Quote: "Don’t make excuses. Make things happen. Make changes. Then make history."},
{Author: "Steven Grayhm", Quote: "Excuses are the tools with which persons with no purpose in view build for themselves great monuments of nothing."},
{Author: "Dave Del Dotto", Quote: "No one ever excused his way to success."},
{Author: "Bo Bennett", Quote: "Not managing your time and making excuses are two bad habits. Don’t put them both together by claiming you ‘don’t have the time’."},
{Author: "Brian Tracy", Quote: "You can make excuses or you can make progress. You choose."},
{Author: "Zig Ziglar", Quote: "Put all your excuses aside and remember this: YOU are capable."},
{Author: "George W. Carver", Quote: "Ninety-nine percent of the failures comes from people who have the habit of making excuses."},
{Author: null, Quote: "In essence, if we want to direct our lives, we must take control of our consistent actions. It’s not what we do once in a while that shapes our lives, but what we do consistently. — Tony Robbins"},
{Author: "Greg Hickman", Quote: "Don’t make excuses, make something incredible happen in your life right now."},
{Author: "Robert H. Schuller", Quote: "Negative thinking is subtle and deceptive. It wears many faces and hides behind the mask of excuses. It is important to strip away the mask and discover the real, root emotion."},
{Author: "Scott Spencer", Quote: "The trouble with excuses, however, is that they become inevitably difficult to believe after they’ve been used a couple of times."},
{Author: "Benjamin Franklin", Quote: "He that is good for making excuses is seldom good for anything else."},
{Author: "James Allen", Quote: "A man sooner or later discovers that he is the master-gardener of his soul, the director of his life."},
{Author: "Henry Ward Beecher", Quote: "Hold yourself responsible for a higher standard than anybody else expects of you, never excuse yourself."},
{Author: "Zig Ziglar", Quote: "Put all excuses aside and remember this: YOU are capable."},
{Author: "Hubert Selby Jr.", Quote: "Eventually we all have to accept full and total responsibility for our actions, everything we have done, and have not done."},
{Author: "Joan Didion", Quote: "The willingness to accept responsibility for one’s own life is the source from which self-respect springs."},
{Author: "Jim Rohn", Quote: "You must take personal responsibility. You cannot change the circumstances, the seasons, or the wind, but you can change yourself. That is something you have charge of."},
{Author: "Criss Jami", Quote: "Like crying wolf, if you keep looking for sympathy as a justification for your actions, you will someday be left standing alone when you really need help."},
{Author: "Wayne Dyer", Quote: "If you have passion, there is no need for excuses because your enthusiasm will trump any negative reasoning you might come up with. Enthusiasm makes excuses a nonissue."},
{Author: "Ken Blanchard", Quote: "When you’re interested in something, you do it only when it’s convenient. When you’re committed to something, you accept no excuses, only results."},
{Author: "not people; to focus your energies on answers", Quote: "It is wise to direct your anger towards problems"},
{Author: "Roy T. Bennett", Quote: "Maturity is when you stop complaining and making excuses in your life; you realize everything that happens in life is a result of the previous choice you’ve made and start making new choices to change your life."},
{Author: "it is an amazing journey", Quote: "The best day of your life is the one on which you decide your life is your own. No apologies or excuses. No one to lean on, rely on, or blame. The gift is yours"},
{Author: "I Ching", Quote: "Work on yourself first, take responsibility for your own progress."},
{Author: "Steve Maraboli", Quote: "Your complaints, your drama, your victim mentality, your whining, your blaming, and all of your excuses have NEVER gotten you even a single step closer to your goals or dreams. Let go of your nonsense. Let go of the delusion that you DESERVE better and go EARN it! Today is a new day!"},
{Author: "Alexander Pope", Quote: "Do you find yourself making excuses when you do not perform? Shed the excuses and face reality. Excuses are the loser’s way out. They will mar your credibility and stunt your personal growth."},
{Author: null, Quote: "Self-discipline, the key to eternal life, is doing something that needs to be done whether or not you find it convenient. Self-discipline is usually motivated by our convictions, our internal hopes, and our desires. — Robert L. Simpson"},
{Author: "Jordan Belfort", Quote: "The only thing standing between you and your goal is the bullshit story you keep telling yourself as to why you can’t achieve it."},
{Author: "Yehuda Berg", Quote: "Personal responsibility is not only recognizing the errors of our ways. Personal responsibility lies in our willingness and ability to correct those errors individually and collectively."},
{Author: "Criss Jami", Quote: "Like crying wolf, if you keep looking for sympathy as a justification for your actions, you will someday be left standing alone when you really need help."},
{Author: "Eleanor Roosevelt", Quote: "In the long run, we shape our lives, and we shape ourselves. The process never ends until we die. And the choices we make are ultimately our own responsibility."},
{Author: "Steve Maraboli", Quote: "The victim mindset dilutes the human potential. By not accepting personal responsibility for our circumstances, we greatly reduce our power to change them."},
{Author: "Jules Renard", Quote: "Failure is not our only punishment for laziness; there is also the success of others."},
{Author: "Jesse Owens", Quote: "We all have dreams. But in order to make dreams come into reality, it takes an awful lot of determination, dedication, self-discipline, and effort."},
{Author: null, Quote: `"No more “I’ll do it tomorrow”.
No more “Buts …”
No more “I can’t”.
No more “It’s too hard”.
No more “I’m too tired”.
No more “Waiting for it to get easier”.
No more “Putting it off”.
No more “I don’t have enough money”.
No more “I’m not good enough”.
No more “I would if I….”
No more excuses."`}
]

module.exports = seedData2