const exercises = [
{muscleGroup: "Chest", muscleName: "Pectoralis",        exerciseTitle: "Barbell Bench Presses",     exerciseType: "Power-Lift", spotter: TRUE},
{muscleGroup: "Chest", muscleName: "Pectoralis",        exerciseTitle: "Barbell Incline Presses",   exerciseType: "Power-Lift", spotter: TRUE},
{muscleGroup: "Chest", muscleName: "Pectoralis",        exerciseTitle: "Dumbbell Bench Press",      exerciseType: "Power-Lift", spotter: FALSE},
{muscleGroup: "Chest", muscleName: "Pectoralis",        exerciseTitle: "Dumbell Incline Press",     exerciseType: "Power-Lift", spotter: FALSE},
{muscleGroup: "Chest", muscleName: "Pectoralis",        exerciseTitle: "Dumbbell Flyes",            exerciseType: "Power-Lift", spotter: FALSE},
{muscleGroup: "Chest", muscleName: "Pectoralis",        exerciseTitle: "Cable Crossovers(Mid)",     exerciseType: "Machine", spotter: FALSE},
{muscleGroup: "Chest", muscleName: "Pectoralis",        exerciseTitle: "Cable Crossovers(Low)",     exerciseType: "Machine", spotter: FALSE},
{muscleGroup: "Chest", muscleName: "Pectoralis",        exerciseTitle: "Cable Crossovers(High)",    exerciseType: "Machine", spotter: FALSE},
{muscleGroup: "Back",  muscleName: "Latissimus Dorsi",  exerciseTitle: "Pull-Ups",                  exerciseType: "Power-Lift", spotter: FALSE},
{muscleGroup: "Back",  muscleName: "Latissimus Dorsi",  exerciseTitle: "Wide-Grip Lat PullDown",    exerciseType: "Machine", spotter: FALSE},
{muscleGroup: "Back",  muscleName: "Latissimus Dorsi",  exerciseTitle: "One-Arm Dumbbell Row",      exerciseType: "Power-Lift", spotter: FALSE},
{muscleGroup: "Back",  muscleName: "Latissimus Dorsi",  exerciseTitle: "Seated Cable Rows",         exerciseType: "Machine", spotter: FALSE},
{muscleGroup: "Back",  muscleName: "Latissimus Dorsi",  exerciseTitle: "Straight Arm Pulldowns",    exerciseType: "Machine", spotter: FALSE},
{muscleGroup: "Arms",  muscleName: "Biceps",            exerciseTitle: "Dumbbell Curls",            exerciseType: "Power-Lift", spotter: FALSE},
{muscleGroup: "Arms",  muscleName: "Biceps",            exerciseTitle: "Barbell Curls",             exerciseType: "Power-Lift", spotter: FALSE},
{muscleGroup: "Arms",  muscleName: "Biceps",            exerciseTitle: "Preacher Curls",            exerciseType: "Power-Lift", spotter: FALSE},
{muscleGroup: "Arms",  muscleName: "Biceps",            exerciseTitle: "Concentration Curls",       exerciseType: "Power-Lift", spotter: FALSE},
{muscleGroup: "Arms",  muscleName: "Biceps",            exerciseTitle: "Cable Curls",               exerciseType: "Machine", spotter: FALSE},
{muscleGroup: "Arms",  muscleName: "Biceps",            exerciseTitle: "Hammer Curls",              exerciseType: "Power-Lift", spotter: FALSE},
{muscleGroup: "Arms",  muscleName: "Triceps",           exerciseTitle: "Seated Triceps Presses",    exerciseType: "Power-Lift", spotter: FALSE},
{muscleGroup: "Arms",  muscleName: "Triceps",           exerciseTitle: "Lying Triceps Presses",     exerciseType: "Power-Lift", spotter: FALSE},
{muscleGroup: "Arms",  muscleName: "Triceps",           exerciseTitle: "Tricep Kickbacks",          exerciseType: "Power-Lift", spotter: FALSE},
{muscleGroup: "Arms",  muscleName: "Triceps",           exerciseTitle: "Tricep Pushdowns",          exerciseType: "Machine", spotter: FALSE},
{muscleGroup: "Arms",  muscleName: "Triceps",           exerciseTitle: "Cabel Extensions",          exerciseType: "Machine", spotter: FALSE},
{muscleGroup: "Arms",  muscleName: "Triceps",           exerciseTitle: "BenchDips",                 exerciseType: "Machine", spotter: FALSE},
{muscleGroup: "Legs",  muscleName: "Quadraceps",        exerciseTitle: "Barbell Squats",            exerciseType: "Power-Lift", spotter: TRUE},
{muscleGroup: "Legs",  muscleName: "Quadraceps",        exerciseTitle: "Leg Presses",               exerciseType: "Machine", spotter: FALSE},
{muscleGroup: "Legs",  muscleName: "Quadraceps",        exerciseTitle: "Leg Extensions",            exerciseType: "Machine", spotter: FALSE},
{muscleGroup: "Legs",  muscleName: "Hamstrings",        exerciseTitle: "Dumbbell Lunges",           exerciseType: "Power-Lift", spotter: FALSE},
{muscleGroup: "Legs",  muscleName: "Hamstrings",        exerciseTitle: "Straight-Leg Deadlifts",    exerciseType: "Power-Lift", spotter: TRUE},
{muscleGroup: "Legs",  muscleName: "Hamstrings",        exerciseTitle: "Lying Leg Curls",           exerciseType: "Machine", spotter: FALSE},
{muscleGroup: "Legs",  muscleName: "Calves",            exerciseTitle: "Seated Calf Raises",        exerciseType: "Machine", spotter: FALSE},
{muscleGroup: "Legs",  muscleName: "Calves",            exerciseTitle: "Standing Heel Raises",      exerciseType: "Power-Lift", spotter: FALSE},
{muscleGroup: "Core",  muscleName: "Abdominals",        exerciseTitle: "Floor Crunches",            exerciseType: "Cardio", spotter: FALSE},
{muscleGroup: "Core",  muscleName: "Abdominals",        exerciseTitle: "Oblique Floor Crunches",    exerciseType: "Cardio", spotter: FALSE},
{muscleGroup: "Core",  muscleName: "Abdominals",        exerciseTitle: "Decline Crunches",          exerciseType: "Cardio", spotter: FALSE},
{muscleGroup: "Core",  muscleName: "Abdominals",        exerciseTitle: "Decline Oblique",           exerciseType: "Cardio", spotter: FALSE},
{muscleGroup: "Core",  muscleName: "Abdominals",        exerciseTitle: "Hanging Knee Raises",       exerciseType: "Cardio", spotter: FALSE},
{muscleGroup: "Core",  muscleName: "Abdominals",        exerciseTitle: "Reverse Crunches",          exerciseType: "Cardio", spotter: FALSE},
{muscleGroup: "Core",  muscleName: "Abdominals",        exerciseTitle: "Cable Crunches",            exerciseType: "Cardio", spotter: FALSE},
{muscleGroup: "Core",  muscleName: "Abdominals",        exerciseTitle: "Cable Oblique Crunches",    exerciseType: "Cardio", spotter: FALSE},
{muscleGroup: "Legs",  muscleName: "Glutes",            exerciseTitle: "Romanian Deadlift",         exerciseType: "Power-Lift", spotter: TRUE},
{muscleGroup: "Legs",  muscleName: "Glutes",            exerciseTitle: "Single-Leg-RDL",            exerciseType: "Power-Lift", spotter: TRUE},
{muscleGroup: "Legs",  muscleName: "Glutes",            exerciseTitle: "Sumo Deadlift",             exerciseType: "Power-Lift", spotter: TRUE},
{muscleGroup: "Legs",  muscleName: "Glutes",            exerciseTitle: "Single-Leg Bridge",         exerciseType: "Cardio", spotter: FALSE},
{muscleGroup: "Legs",  muscleName: "Glutes",            exerciseTitle: "Hip Thrusts",               exerciseType: "Power-Lift", spotter: FALSE},
{muscleGroup: "Legs",  muscleName: "Glutes",            exerciseTitle: "Back Extensions",           exerciseType: "Cardio", spotter: FALSE},
{muscleGroup: "Legs",  muscleName: "Glutes",            exerciseTitle: "Cable Pull-Through",        exerciseType: "Machine", spotter: FALSE},
{muscleGroup: "Legs",  muscleName: "Glutes",            exerciseTitle: "Kettlebell Swings",         exerciseType: "Power-Lift", spotter: FALSE},
{muscleGroup: "Cardio", muscleName: "Cardio",           exerciseTitle: "Treadmill",                 exerciseType: "Cardio", spotter: FALSE},
{muscleGroup: "Cardio", muscleName: "Cardio",           exerciseTitle: "Bike",                      exerciseType: "Cardio", spotter: FALSE},
{muscleGroup: "Cardio", muscleName: "Cardio",           exerciseTitle: "Jogging",                   exerciseType: "Cardio", spotter: FALSE},
{muscleGroup: "Cardio", muscleName: "Cardio",           exerciseTitle: "Swimming",                  exerciseType: "Cardio", spotter: FALSE},
{muscleGroup: "Cardio", muscleName: "Cardio",           exerciseTitle: "Eliptical",                 exerciseType: "Cardio", spotter: FALSE},
]

module.exports = exercises