{Author: null, Quote: "The best project you’ll ever work on is YOU."},
{Author: null, Quote: "Look in the mirror: that’s your competition."},
{Author: null, Quote: "You said tomorrow yesterday."},
{Author: null, Quote: "Decide, Commit, Succeed."},
{Author: null, Quote: "No excuses; Just results."},
{Author: null, Quote: "You don’t find will power, you create it."},
{Author: null, Quote: "Your largest fear carries your greatest growth."},
{Author: null, Quote: "Nothing tastes as good as skinny feels."},
{Author: null, Quote: "The body achieves what the mind believes."},
{Author: null, Quote: "If you’re tired of starting over, stop giving up."},
{Author: null, Quote: "Three months from now, you will thank yourself."},
{Author: null, Quote: "It’s not just the weight you lose: but the life you gain."},
{Author: null, Quote: "A healthy outside starts from the inside. – Robert Urich"},
{Author: null, Quote: "Push yourself because, no one else is going to do it for you."},
{Author: null, Quote: "Once you control your mind you can conquer your body."},
{Author: null, Quote: "When you find your why, you find a way to make it happen. – Eric Thomas"},
{Author: null, Quote: "If it is important to you, you will find a way; If not, you’ll find an excuse."},
{Author: null, Quote: "Losing weight is hard; Maintaining weight is hard; Staying overweight is hard; Choose your hard."},
{Author: null, Quote: "Your only limit is you."},
{Author: null, Quote: "It never gets easier. You just get better. – Jordan Hoechlin"},
{Author: null, Quote: "You aren’t fat. You have fat. Fat does not define you."},
{Author: null, Quote: "It is the things we work hardest for that will reward us the most."},
{Author: null, Quote: "Being healthy isn’t about the weight you lose, it’s about the life you gain."},
{Author: null, Quote: "If you want to get fit, you have to give away only one thing. Your excuses."},
{Author: null, Quote: "The struggle you’re in today is developing the strength you need for tomorrow."},
{Author: null, Quote: "Discipline is choosing between what you want now and what you want most."},
{Author: null, Quote: "You are not just doing it for yourself. Your transformation can inspire others."},
{Author: null, Quote: "If you want something you’ve never had, then you’ve got to do something you’ve never done."},
{Author: null, Quote: "You’ve always been beautiful. Now you’re just deciding to be healthier, fitter, faster and stronger. Remember that."},
{Author: null, Quote: "There are two primary choices in life: to accept conditions as they exist, or accept the responsibility for changing them. – Dr. Denis Waitley"},
{Author: null, Quote: "To lose weight permanently requires faith – faith there is a bigger life waiting for you beyond food and weight. – Catherine L. Taylor"},
{Author: null, Quote: "Strength doesn’t come from what you can do. It comes from overcoming the things you once thought you couldn’t. – Nikki Rogers"},
{Author: null, Quote: "There are only two options regarding commitment; you’re either in or you’re out. There’s no such thing as life in-between. – Pat Riley"},
{Author: null, Quote: "The reason why people give up so fast is because they tend to look at how far they still have to go, instead of how far they have gotten."},
{Author: null, Quote: "Obstacles don’t have to stop you. If you run into a wall, don’t turn around and give up. Figure out how to climb it, go through it, or work around it. – Michael Jordan"},
{Author: null, Quote: "Unless you puke, faint, or die, keep going. – Jillian Michaels"},
{Author: null, Quote: "Wake up with determination. Go to bed with satisfaction."},
{Author: null, Quote: "Success is what comes after you stop making excuses. – Luis Galarza"},
{Author: null, Quote: "Eat for the body you want, not for the body you have."},
{Author: null, Quote: "It is not easy, but it is worth it. Now repeat that everyday."},
{Author: null, Quote: "One workout at a time. One day at a time. One meal at a time."},
{Author: null, Quote: "Junk food satisfies you for a minute. Being fit satisfies you for life."},
{Author: null, Quote: "You were strong enough to get this far. You are strong enough to keep going."},
{Author: null, Quote: "Just 21 days, 21 days of healthy eating and working out, and it will become habit."},
{Author: null, Quote: "In two weeks, you’ll feel it. In four weeks, you’ll see it. In eight weeks, you’ll hear it."},
{Author: null, Quote: "Your body can stand up to almost anything. It’s your mind that you have to convince."},
{Author: null, Quote: "Fattening food satisfies you for a few minutes … Feeling good about yourself lasts forever."},
{Author: null, Quote: "The first step to getting what you want is having the courage to get rid of what you don’t."},
{Author: null, Quote: "Most people fail, not because of lack of desire, but, because of lack of commitment. – Vince Lombardi"},
{Author: null, Quote: "Junk food you’ve craved for an hour, or the body you’ve craved for a lifetime? Your decision."},
{Author: null, Quote: "It took more than a day to put it on. It will take more than a day to take it off. Keep going."},
{Author: null, Quote: "I will NOT feel deprived when I bypass junk food. I will feel empowered that I made the healthy choice."},
{Author: null, Quote: "If I quit now I will soon be back to where I started. And when I started, I was desperate to get to where I am now."},
{Author: null, Quote: "This month’s diet is next month’s body."},
{Author: null, Quote: "Don’t let a bad day turn into a bad week."},
{Author: null, Quote: "Nothing tastes as good as healthy feels."},
{Author: null, Quote: "It is not the mountain we conquer, but ourselves. – Sir Edmund Hillary"},
{Author: null, Quote: "I may not be there yet, but I’m closer than I was yesterday."},
{Author: null, Quote: "Every small achievement will soon be one amazing success."},
{Author: null, Quote: "Wanting something is not enough. You must hunger for it. – Les Brown"},
{Author: null, Quote: "Do something now; your future self will thank you for later."},
{Author: null, Quote: "Suffer the pain of self-discipline. Or suffer the pain of regret. – Jim Rohn"},
{Author: null, Quote: "You have to be at your strongest when you’re feeling at your weakest."},
{Author: null, Quote: "Your diet is a bank account. Good food choices are good investments. – Bethenny Frankel"},
{Author: null, Quote: "Never stop trying. Never stop believing. Never give up. Your day will come."},
{Author: null, Quote: "I’m not telling you it is going to be easy, I’m telling you it’s going to be worth it. – Art Williams"},
{Author: null, Quote: "Fear says… no you can’t. Determination says… yes you can. Results say… I told you so."},
{Author: null, Quote: "Everything you can imagine about how you will look and feel when you lose weight is real. – Felicity Luckey"},
{Author: null, Quote: "Sometimes you don’t realize your own strength until you come face to face with your greatest weakness. – Susan Gale"},
{Author: null, Quote: "Believe in new possibilities."},
{Author: null, Quote: "You are stronger than you think."},
{Author: null, Quote: "Once you choose hope, anything’s possible. – Christopher Reeve"},
{Author: null, Quote: "In the middle of a difficulty lies opportunity. – Albert Einstein"},
{Author: null, Quote: "Believe you can and you’re halfway there. – Theodore Roosevelt"},
{Author: null, Quote: "A little progress each day adds up to big results. – Satya Nani"},
{Author: null, Quote: "Every morning you wake up is another chance to get it right."},
{Author: null, Quote: "Your body hears everything your mind says. Stay positive."},
{Author: null, Quote: "What you tell yourself every day will either lift you up or tear you down."},
{Author: null, Quote: "Don’t think about what might go wrong. Think about what might go right."},
{Author: null, Quote: "Never stop trying. Never stop believing. Never give up. Your day will come."},
{Author: null, Quote: "Results happen over time, not overnight. Work hard, stay consistent, and be patient."},
{Author: null, Quote: "If you believe it will work out, you’ll see opportunities. If you believe it won’t, you will see obstacles. – Wayne Dyer"},
{Author: null, Quote: "If the plan doesn’t work, change the plan but never the goal."},
{Author: null, Quote: "Focus on your goal. Don’t look in any direction but ahead."},
{Author: null, Quote: "You don’t get what you wish for. You get what you work for."},
{Author: null, Quote: "Be stubborn about your goals and flexible about your methods."},
{Author: null, Quote: "Discipline is the bridge between goals and accomplishments. – Jim Rohn"},
{Author: null, Quote: "You don’t want to look back on your life and know you could have done better."},
{Author: null, Quote: "Set a goal so big that you can’t achieve it until you grow into the person who can."},
{Author: null, Quote: "The pain of the process is only temporary, but the feeling of achievement lasts forever."},
{Author: null, Quote: "Weight loss doesn’t begin in the gym with a dumb bell; it starts in your head with a decision. ― Toni Sorenson"},
{Author: null, Quote: "Only put off starting a weight loss program until tomorrow if you are willing to die without having achieved your weight loss goals.- Felicity Luckey"},
{Author: null, Quote: "Self-discipline is about controlling your desires and impulses while staying focused on what needs to get done to achieve your goal. – Adam Sicinski"},
{Author: null, Quote: "One of the most important keys to success and achieving your goals is having the discipline to do what you know you should do, even when you don’t feel like doing it."},
{Author: null, Quote: "Don’t stop until you’re proud."},
{Author: null, Quote: "Pain is temporary. Quitting lasts forever."},
{Author: null, Quote: "Don’t give up on yourself. You’re worth it."},
{Author: null, Quote: "Tough times don’t last. Tough people do. – Robert H. Schuller"},
{Author: null, Quote: "Hope never abandons you, you abandon it. – George Weinberg"},
{Author: null, Quote: "When you feel like quitting, think about why you started."},
{Author: null, Quote: "Be strong when you are weak & brave when you are scared."},
{Author: null, Quote: "Never stop trying. Never stop believing. Never give up. Your day will come."},
{Author: null, Quote: "Determination is doing what needs to be done even when you don’t feel like doing it."},
{Author: null, Quote: "Eat less sugar, you’re sweet enough already."},
{Author: null, Quote: "Do not reward yourself with food, you’re not a dog."},
{Author: null, Quote: "Suck it up and one day you won’t have to suck it in."},
{Author: null, Quote: "Note to myself: When I eat like crap, I feel like crap."},
{Author: null, Quote: "Dear Stomach, you’re bored, not hungry. So shut up."},
{Author: null, Quote: "You are what you eat – so don’t be Fast, Cheap, Easy, or Fake."},
{Author: null, Quote: "No matter how slow you go, you are still lapping everybody on the couch."},
{Author: null, Quote: "You can’t expect to look like a million bucks if you eat from the dollar menu."},
{Author: null, Quote: "I’m not losing weight. I’m getting rid of it. I have no intention of finding it again."},
{Author: null, Quote: "Your body is the baggage you must carry through life. The more excess the baggage, the shorter the trip. – Arnold H. Glasgow"},
{Author: null, Quote: "Saying “Oh, I’ve already ruined my good eating today. I’ll just eat crap” is like saying “Oh, I dropped my phone on the floor. I’ll just smash it till it breaks.”"},
{Author: null, Quote: "What you eat in private eventually is what you wear in public. Eat clean, look lean."},
{Author: null, Quote: "Junk food you’ve craved for an hour, or the body you’ve craved for a lifetime? Your decision."},
{Author: null, Quote: "Those who think they have no time for healthy eating will sooner or later have to find time for illness."},
{Author: null, Quote: "Respect your body. Fuel your body. Challenge your body. Move your body. And most of all, love your body."},
{Author: null, Quote: "Even if you can’t physically see the results in front of you, every single effort is changing your body from the inside."},
{Author: null, Quote: "If you are really serious about losing weight, you need to be completely honest with yourself about what you’re eating."},
{Author: null, Quote: "Losing weight is a mental challenge, not a physical one. If you can take control of your mind and body, the weight loss will follow."},
{Author: null, Quote: "While weight loss is important, what’s more important is the quality of food you put in your body – food is information that quickly changes your metabolism and genes. – Dr. Mark Hyman"},
{Author: null, Quote: "When you look in the mirror and see no change, and still keep faith, knowing that in time you will get there if you stay focused and on track, that’s the difference between those who succeed and those who fail."},
{Author: null, Quote: "Weight loss can change your whole character. That always amazed me: Shedding pounds does change your personality. It changes your philosophy of life because you recognize that you are capable of using your mind to change your body. – Jean Nidetch"},
{Author: null, Quote: "Exercise to be fit, not skinny. Eat to nourish your body and always ignore the haters, doubters and unhealthy examples that were once feeding you. You are worth more than you realize."},
{Author: null, Quote: "There’s a difference between interest and commitment. When you’re interested in doing something, you do it only when it’s convenient. When you’re committed to something, you accept no excuses; only results. – Kenneth Blanchard"},
{Author: null, Quote: "Remember how your clothes don’t fit, your body feels sluggish, your skin doesn’t glow, you don’t have energy, you want to feel beautiful, you’re regretting what you ate, you’re wishing you worked out, you wanted to change, before making another unhealthy choice."},
{Author: null, Quote: "Want to lose weight? Do more than just think about it. You don’t need to hold off while you keep searching for an abundance of motivation to lose weight. What you need is an abundance of action! – Shawn Weeks"},
{Author: null, Quote: "Dear Me,
I am not going to lose all this weight in a week. Heck, I probably won’t even lose it in a month. But, I am going to start eating great and working out for the rest of my life, not one week or just one month."},
{Author: null, Quote: "Don’t wait until everything is just right. It will never be perfect. There will always be challenges, obstacles and less than perfect conditions. So what. Get started now. With each step you take, you will grow stronger and stronger, more and more skilled, more and more self-confident and more and more successful. – Mark Victor Hansen"},
{Author: null, Quote: "When your body absorbs toxins, it stores them in fat, which is why fiber and probiotics are strategic weapons for weight loss. Fiber keeps your colon healthy and reduces your body’s absorption of toxins. – Suzanne Somers"},
,
{Author: "Anonymous", Quote: "No more negative body thoughts.
No more “I’ll do it tomorrow”.
No more sitting and wishing for a thinner me.
No more eating when I am not hungry.
No more waiting for this to get easier.
No more muffin tops,
No more wobbly thighs.
No more soft, round stomach,
No more “Buts…”.
No more “I can’t”.
No more “It’s too hard”.
No more “I’m too tired”.
No more excuses."},
{Author: "Anonymous", Quote: "Never quit.
If you stumble get back up.
What happened yesterday no longer matters.
Today’s another day.
So get back on track and
Move closer to your dreams and goals.
You can do it."},
{Author: "Anonymous", Quote: "Dear Body,
I’m sorry I’ve treated you this way, feeding you the wrong foods and not taking care of you. I promise to do better and get you back to the best shape and fitness level you can be. We can do it!
Sincerely,
Me."}